import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import ChatIcon from '@/components/chat_icon'; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-commerce website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <ChatIcon />
      </body>
    </html>
  );
}
