export const API_BASE_URL = "http://localhost:8000";

export const API_ROUTES = {
  LOGIN: "/users/login",
  SIGNUP: "/users/signup",
  CHANGE_PASSWORD: "/users/change_password",
  FORGOT_PASSWORD: "/users/forgot_password",
  PASSWORD_CODE_VALIDATE: "/users/validate_temp_code",
  CHANGE_PASSWORD_WITH_CODE: "/users/change_password_with_code",
  GET_CURRENT_USER: "/users/get_current_user",
  UPDATE_CURRENT_USER: "/users/update_user",
  SHOPS_NUMBER: "/admin/get_number_shops",
  REVENUE_CURRENT: "/admin/get_current_revenue",
  USERS_NUMBER: "/admin/get_number_user",
  INCOME_STATS: "/admin/statistics_income",
  CAT_STATS: "/admin/statistics_category",
  ORDER_STATS: "/admin/statistics_number_orders",
  CREATE_ADMIN: "/admin/create_admin",
  GET_GOOGLE_LOGIN: "/users/get_google_login",
  CHAT_MESSAGE: "/ai/chatbot",
  GET_ALL_PRODUCT: "/products/all",
  GET_PRODUCT_DETAIL: "/products",
  GET_SEARCH_PRODUCTS: "/products/search_products",
  ADD_PRODUCT_TO_CART: "/cart/update_products",
  GET_PRODUCT_IN_CART: "/cart/get_cart_details",
  ORDER_PRODUCT: "/order/order_products",
  UPDATE_CART: "/cart/update_products",
  SHOP_REVENUE_STATS: "/shops/statistics/revenue",
  SHOP_TOP_PRODUCTS_STATS: "/shops/statistics/top_products",
  SHOP_CATEGORIES_STATS: "/shops/statistics/categories",
  GET_ORDER_BY_ID: "/order/get_order_by_id",
  RESTORE_ORDER: "/order/restore",
  GET_ALL_PRODUCTS_SHOP: "/products/get_all_products_shop",
  GET_ORDER_HISTORY: "/order/get_order_history",
};
